name: flutter_js
description: A Javascript engine to use with flutter. 
  It uses Quickjs on Android and JavascriptCore on IOS
version: 0.2.4+0
homepage: https://github.com/abner/flutter_js
repository: https://github.com/abner/flutter_js

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ">=1.0.0 < 2.0.0"
  http: ">=0.12.0 <1.0.0"
  sync_http: ">=0.2.0 <0.4.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.abner.flutter_js
        pluginClass: FlutterJsPlugin
      ios:
        pluginClass: FlutterJsPlugin
      linux:
        pluginClass: FlutterJsPlugin

  assets:
    - assets/js/



